export const crudlistemptytable = {
    "stepid": "541C34B5-4F6E-4316-BA16-6940ACD90C44",
    "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
    "crudname": "View Future Detail",
    "reviewrequired": 0,
    "nextstructtype": "StepWithSoftwareUser",
    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
    "parentobjname": "step",
    "childobjname": "crud",
    "parentid": "stepid",
    "childid": "stepid",
    "crudlist": [
        {
            "crudlistid": "DA58270E-D38F-40A9-9EB8-0F0B6088AD4D",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "label": "Scheduled Details",
            "idcolumn": "DetailID",
            "type": "tolist",
            "actionlabel": "",
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDAction] @WorkflowID = '%v', @StepID = '%v',@SoftwareUserID = '%v' ",
            "parentobjname": "crud",
            "childobjname": "crudlist",
            "parentid": "crudid",
            "childid": "crudid",
            "crudaction": [
                {
                    "crudactionid": "A30B0C03-B92F-4E59-9035-222F47B18E9A",
                    "crudlistid": "DA58270E-D38F-40A9-9EB8-0F0B6088AD4D",
                    "label": "Edit Detail",
                    "type": 2,
                    "peritem": 1,
                    "workflowid": "352E1FD3-AFEB-4C0A-AC57-388407D4DD7D",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "crudaction",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "crudactionid": "6D01C28D-D2E7-4878-9B69-7FE40BAA11E2",
                    "crudlistid": "DA58270E-D38F-40A9-9EB8-0F0B6088AD4D",
                    "label": "Request A Detail",
                    "type": 2,
                    "peritem": 0,
                    "workflowid": "3CD978AF-CBBC-47F8-A46F-A8B761B8EB24",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "crudaction",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "crudactionid": "73EF2D31-559B-4AFD-8F6B-B5646A9D2878",
                    "crudlistid": "DA58270E-D38F-40A9-9EB8-0F0B6088AD4D",
                    "label": "Cancel Detail",
                    "type": 2,
                    "peritem": 1,
                    "workflowid": "63159D8E-8DF9-459F-A40C-A47FA76B1ABE",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "crudaction",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                }
            ],
            "crudlistitems": []
        }
    ],
    "crudcolumn": [
        {
            "crudcolumnid": "CA80A7C8-9E4D-4B36-BC6D-040DFCE6EECE",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "7E4FA6DD-BA9B-407A-BFF8-D9427F82F2D4",
            "label": "Start Date",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 1,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "7E4FA6DD-BA9B-407A-BFF8-D9427F82F2D4",
                    "sequence": 1,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Start Date",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "date",
                    "datatype": "datetime",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "StartDate",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "ca80a7c8-9e4d-4b36-bc6d-040dfce6eece"
        },
        {
            "crudcolumnid": "DFC8FDDD-EB20-4B38-8BF8-0880314E627C",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "A00C5486-1540-4B1E-AAB0-989DF372564D",
            "label": "End Date",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 2,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "A00C5486-1540-4B1E-AAB0-989DF372564D",
                    "sequence": 2,
                    "selectoptions": "",
                    "required": 0,
                    "label": "End Date",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "date",
                    "datatype": "datetime",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "EndDate",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "dfc8fddd-eb20-4b38-8bf8-0880314e627c"
        },
        {
            "crudcolumnid": "3A13FCAA-2A53-42A1-9D17-125E9DEB3A35",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "A703A554-8737-451F-BB9B-6866CED97C9B",
            "label": "Start Time",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 3,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "A703A554-8737-451F-BB9B-6866CED97C9B",
                    "sequence": 3,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Start Time",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "time",
                    "datatype": "datetime",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "StartTime",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "3a13fcaa-2a53-42a1-9d17-125e9deb3a35"
        },
        {
            "crudcolumnid": "C4AC2BD4-C74E-4CBA-890C-17A519D41AA1",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "7CA26F81-12A8-490D-8903-0403B8850BC2",
            "label": "End Time",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 4,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "7CA26F81-12A8-490D-8903-0403B8850BC2",
                    "sequence": 4,
                    "selectoptions": "",
                    "required": 0,
                    "label": "End Time",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "time",
                    "datatype": "datetime",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "EndTime",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "c4ac2bd4-c74e-4cba-890c-17a519d41aa1"
        },
        {
            "crudcolumnid": "700D880B-725A-48B9-BBA7-185AE4AC84AF",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "9CBDBAAE-3B77-4BB0-BE7D-87B6F00EDE4E",
            "label": "Location",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 5,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "9CBDBAAE-3B77-4BB0-BE7D-87B6F00EDE4E",
                    "sequence": 5,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Location",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Location",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "700d880b-725a-48b9-bba7-185ae4ac84af"
        },
        {
            "crudcolumnid": "43FCD9CD-CD75-4772-A993-269147C58847",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "969D54CC-04F8-4B63-B708-F5163CD6DF89",
            "label": "Openings",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 6,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "969D54CC-04F8-4B63-B708-F5163CD6DF89",
                    "sequence": 6,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Openings",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "int",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Openings",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "43fcd9cd-cd75-4772-a993-269147c58847"
        },
        {
            "crudcolumnid": "1EB99581-8069-46F6-8618-5393D6E28151",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "E2148A09-2FCE-4149-B1AE-832DBBF17791",
            "label": "Filled",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 7,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "E2148A09-2FCE-4149-B1AE-832DBBF17791",
                    "sequence": 7,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Filled",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "int",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Filled",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "1eb99581-8069-46f6-8618-5393d6e28151"
        },
        {
            "crudcolumnid": "D46C9921-7868-438A-8712-7861E001948C",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "D39F93DB-8390-447F-BC12-8BEF433A863A",
            "label": "Officers",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 8,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "D39F93DB-8390-447F-BC12-8BEF433A863A",
                    "sequence": 8,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Officers",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Officers",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "d46c9921-7868-438a-8712-7861e001948c"
        },
        {
            "crudcolumnid": "08C43C56-9376-4851-9199-BFA294AFD978",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "B515D26A-874E-481D-9FFF-B88056F123B5",
            "label": "Agency Name",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 9,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "B515D26A-874E-481D-9FFF-B88056F123B5",
                    "sequence": 9,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Agency Name",
                    "validminimum": 1,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "AgencyName",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "08c43c56-9376-4851-9199-bfa294afd978"
        },
        {
            "crudcolumnid": "8FFCA1AE-0859-4734-A95C-20B957DABC8D",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "264FF33F-8FCF-4C85-A47B-A4E39AB89EE8",
            "label": "Customer Name",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 10,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "264FF33F-8FCF-4C85-A47B-A4E39AB89EE8",
                    "sequence": 10,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Customer Name",
                    "validminimum": 1,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "CustomerName",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "8ffca1ae-0859-4734-a95c-20b957dabc8d"
        },
        {
            "crudcolumnid": "23823CCB-0D99-4C80-A39B-C52AD1617725",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "D1FF9FBF-1815-462C-A42A-3224E0F57705",
            "label": "Note",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 11,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "D1FF9FBF-1815-462C-A42A-3224E0F57705",
                    "sequence": 11,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Note",
                    "validminimum": 0,
                    "validmaximum": 999999,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Note",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "23823ccb-0d99-4c80-a39b-c52ad1617725"
        },
        {
            "crudcolumnid": "10CC4A6E-3B9A-4CCB-9A37-D456572E70C4",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "C5FEEBF3-4010-42DC-9DA9-C48BEA5E09C2",
            "label": "Holds",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 12,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "C5FEEBF3-4010-42DC-9DA9-C48BEA5E09C2",
                    "sequence": 12,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Holds",
                    "validminimum": 1,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Holds",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "10cc4a6e-3b9a-4ccb-9a37-d456572e70c4"
        },
        {
            "crudcolumnid": "9CDEAFBE-0943-4D12-9F1E-E85EF060B5AA",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "4080FFA4-72C5-4621-AF54-A29448C32FCE",
            "label": "Contact Name",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 13,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "4080FFA4-72C5-4621-AF54-A29448C32FCE",
                    "sequence": 13,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Contact Name",
                    "validminimum": 1,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ContactName",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "9cdeafbe-0943-4d12-9f1e-e85ef060b5aa"
        },
        {
            "crudcolumnid": "C4C8E2AA-1383-4BD0-8A74-E8C4F58799F0",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "DE689274-8468-497A-8769-3406B4E7F179",
            "label": "Contact Email",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 14,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "DE689274-8468-497A-8769-3406B4E7F179",
                    "sequence": 14,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Contact Email",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "email",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ContactEmail",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "c4c8e2aa-1383-4bd0-8a74-e8c4f58799f0"
        },
        {
            "crudcolumnid": "5624D8EB-F707-469A-B8EA-ED884F0018B8",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "47F7F78F-4C1E-4FDE-8BE2-6E3993EF2F0C",
            "label": "Contact Phone Number",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 15,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "47F7F78F-4C1E-4FDE-8BE2-6E3993EF2F0C",
                    "sequence": 15,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Contact Phone Number",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "phone",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ContactPhoneNumber",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "5624d8eb-f707-469a-b8ea-ed884f0018b8"
        },
        {
            "crudcolumnid": "9E1637F9-0F01-4100-860E-F31AA1B8F20A",
            "crudid": "D8F75803-67CF-4719-9894-6D8D135DB8AD",
            "formelementid": "DCA6ECC4-9778-45BE-8DAF-2C6355650B42",
            "label": "Contact Role",
            "iscolumn": 1,
            "isfilter": 1,
            "sequence": 16,
            "nextstructtype": "StepWithSoftwareUser",
            "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "formelement": [
                {
                    "formelementid": "DCA6ECC4-9778-45BE-8DAF-2C6355650B42",
                    "sequence": 16,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Contact Role",
                    "validminimum": 1,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 1,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ContactRole",
                    "nextstructtype": "StepWithSoftwareUser",
                    "nextsp": "exec [spxd_CRUD_Get_Future_Detail_CRUDList_CRUDListItems] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v' ",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "id": "9e1637f9-0f01-4100-860e-f31aa1b8f20a"
        }
    ]
}