export const crudlisttesttransfering =
{
    "stepid": "324CBBF3-D4F8-4D46-9E81-08E4027B8FB6",
    "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
    "crudname": "Detail Review",
    "reviewrequired": 0,
    "nextstructtype": "StepWithAgency",
    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
    "parentobjname": "step",
    "childobjname": "crud",
    "parentid": "stepid",
    "childid": "stepid",
    "crudlist": [
        {
            "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Flagged",
            "idcolumn": "AssignmentID",
            "type": "fromlist",
            "actionlabel": "",
            "nextstructtype": "StepWithAgency",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDAction] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudlist",
            "parentid": "crudid",
            "childid": "crudid",
            "crudaction": [
                {
                    "crudactionid": "7CD38DD8-5A81-4C29-861F-44F14A533D2E",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "label": "Edit",
                    "type": 2,
                    "peritem": 1,
                    "workflowid": "CF2241B1-DAE7-4695-B05A-ADF1EA405C5E",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CanMoveTo] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "crudaction",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                //   {
                //     "crudactionid": "7CD38DD8-5A81-4C29-861F-44F14A533D2E",
                //     "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                //     "label": "Move Row",
                //     'allowmultipleselections':1,
                //     "type": 'transfer',
                //     "peritem": 1,
                //     "workflowid": "CF2241B1-DAE7-4695-B05A-ADF1EA405C5E",
                //     "nextstructtype": "StepWithAgency",
                //     "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CanMoveTo] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                //     "parentobjname": "crudlist",
                //     "childobjname": "crudaction",
                //     "parentid": "crudlistid",
                //     "childid": "crudlistid"
                // }
            ],
            "canmoveto": [
                {
                    "fromcrudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "tocrudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "canmoveto",
                    "parentid": "crudlistid",
                    "childid": "fromcrudlistid"
                },
                {
                    "fromcrudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "tocrudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "canmoveto",
                    "parentid": "crudlistid",
                    "childid": "fromcrudlistid"
                }
            ],
            "crudlistitems": [
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 111836,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Extra Duty Solutions",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "WF Testing",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Omar Alejandro",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Apr 12 2023",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "11:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "23:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "11:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "23:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 12,
                    "274856d4-b837-450c-9fb1-f20401767872": "123 Jivasoft Ln",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "0AE1CFB7-DACE-4975-8140-393C310E81F6",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 111409,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Extra Duty Solutions",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "WF Testing",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Sam Carey",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Feb 20 2023",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "17:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "01:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "17:57",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "17:57",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 3,
                    "274856d4-b837-450c-9fb1-f20401767872": "Jivasoft HQ",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "8E65B7C3-62C7-4A20-825C-613169B94797",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 102529,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Extra Duty Solutions",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Omar Alejandro",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Dec 25 2022",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "00:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "17:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "00:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "17:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 17,
                    "274856d4-b837-450c-9fb1-f20401767872": "EDS HQ",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "B21617FF-25E3-450B-9238-62A671587E9B",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 102321,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Extra Duty Solutions",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Sam Carey",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Dec 28 2022",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "00:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "17:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "00:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "17:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 17,
                    "274856d4-b837-450c-9fb1-f20401767872": "EDS HQ",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "7DDACBA9-6014-4D42-B12E-62C2877C419F",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 102373,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Extra Duty Solutions",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Omar Alejandro",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Dec 29 2022",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "00:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "17:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "00:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "17:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 17,
                    "274856d4-b837-450c-9fb1-f20401767872": "EDS HQ",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "7B980094-F498-444D-99C3-9462B058E54A",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 111413,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "180 Turn Church",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "Voucher Testing EverSource",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Sam Carey",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Jan 05 2023",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "11:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "17:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "05:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "17:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 12,
                    "274856d4-b837-450c-9fb1-f20401767872": "JivasoftHQ",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "3373C870-89E9-4A8E-8527-E23D54EF1D34",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 111464,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Abundant Life Church",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "Test Job - School",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Wayne Scott",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Mar 13 2023",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "12:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "19:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "12:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "19:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 7,
                    "274856d4-b837-450c-9fb1-f20401767872": "EDS-ISD",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "655EDEF9-4374-42F9-9619-C9ACCFD80C45",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 111506,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Abundant Life Church",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "Test Job - School",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Sam Carey",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Feb 21 2023",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "13:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "20:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "17:59",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "18:01",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 3,
                    "274856d4-b837-450c-9fb1-f20401767872": "EDS-ISD",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "98E24EDA-BE62-42F4-AFE1-F836A34B7196",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                },
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 111845,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "180 Turn Church",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Omar Alejandro",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "May 09 2023",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "11:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "23:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "15:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "03:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 12,
                    "274856d4-b837-450c-9fb1-f20401767872": "999 Jivasoft Dr",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "FLAG",
                    "assignmentid": "4283283E-02D8-4776-BE57-9A366647EBAD",
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                }
            ]
        },
        {
            "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Approved",
            "idcolumn": "AssignmentID",
            "type": "fromlist",
            "actionlabel": "",
            "nextstructtype": "StepWithAgency",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDAction] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudlist",
            "parentid": "crudid",
            "childid": "crudid",
            "crudaction": [],
            "canmoveto": [
                {
                    "fromcrudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "tocrudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "canmoveto",
                    "parentid": "crudlistid",
                    "childid": "fromcrudlistid"
                }
            ],
            "crudlistitems": [
                {
                    "5ed4b082-beac-46a8-a561-05e1ad8cb39c": 111401,
                    "23b6e849-4b36-4c13-bc48-e34a95d37f45": "Greensboro PD NJ - Test",
                    "afaed15e-eb30-4d24-b39d-dde7f4ace37a": "Extra Duty Solutions",
                    "4c169cb6-f0db-48ef-bf3d-2d6dceb8e64f": "Test Job",
                    "f9f78f53-ff18-40d1-842b-558a507ba699": "Omar Alejandro",
                    "2a9d3c04-a0fa-4e59-986a-a8236a0fef21": "Dec 26 2022",
                    "c15f8fe6-e08d-4317-9b3a-3322f6790ba0": "18:00",
                    "edc19b8e-77fa-424a-8bd5-ed8194c691db": "00:00",
                    "a232c55f-54f5-4788-9f39-e9c5eaf7126c": "17:00",
                    "b44b33da-7851-4fa2-8b2f-1b1bf868a9e9": "01:00",
                    "f04e5315-8fd7-441b-90af-b1ef90316a90": 8,
                    "274856d4-b837-450c-9fb1-f20401767872": "EDS HQ",
                    "44051b3f-f127-40e0-8ac7-dc896654562e": "N/A",
                    "assignmentid": "7B9A10EF-29D0-4179-8616-E214D13ADF90",
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "nextstructtype": "",
                    "nextsp": "",
                    "parentobjname": "crudlist",
                    "childobjname": "crudlistitems",
                    "parentid": "crudlistid",
                    "childid": "crudlistid"
                }
            ]
        },
        {
            "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Unreviewed",
            "idcolumn": "AssignmentID",
            "type": "fromlist",
            "actionlabel": "",
            "nextstructtype": "StepWithAgency",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDAction] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudlist",
            "parentid": "crudid",
            "childid": "crudid",
            "crudaction": [],
            "canmoveto": [
                {
                    "fromcrudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "tocrudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudlist",
                    "childobjname": "canmoveto",
                    "parentid": "crudlistid",
                    "childid": "fromcrudlistid"
                }
            ],
            "crudlistitems": []
        }
    ],
    "crudcolumn": [
        {
            "crudcolumnid": "5ED4B082-BEAC-46A8-A561-05E1AD8CB39C",
            "formelementid": "65D3A623-47CC-4188-BCBB-10CE731A76AD",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "JobID",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "65D3A623-47CC-4188-BCBB-10CE731A76AD",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "65D3A623-47CC-4188-BCBB-10CE731A76AD",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "65D3A623-47CC-4188-BCBB-10CE731A76AD",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "65D3A623-47CC-4188-BCBB-10CE731A76AD",
                    "sequence": 10,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Job ID",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "JobID",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "B44B33DA-7851-4FA2-8B2F-1B1BF868A9E9",
            "formelementid": "AF289650-A422-44FA-B817-8373EDF2CA58",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Actual End Time",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "AF289650-A422-44FA-B817-8373EDF2CA58",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "AF289650-A422-44FA-B817-8373EDF2CA58",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "AF289650-A422-44FA-B817-8373EDF2CA58",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "AF289650-A422-44FA-B817-8373EDF2CA58",
                    "sequence": 100,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Actual End Time",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ActualEndTime",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "4C169CB6-F0DB-48EF-BF3D-2D6DCEB8E64F",
            "formelementid": "D8F7C35A-2B8A-4A0A-8188-F2F29AC31F24",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Job Name",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "D8F7C35A-2B8A-4A0A-8188-F2F29AC31F24",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "D8F7C35A-2B8A-4A0A-8188-F2F29AC31F24",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "D8F7C35A-2B8A-4A0A-8188-F2F29AC31F24",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "D8F7C35A-2B8A-4A0A-8188-F2F29AC31F24",
                    "sequence": 40,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Job Name",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "JobName",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "C15F8FE6-E08D-4317-9B3A-3322F6790BA0",
            "formelementid": "57E4DDB1-71D4-4845-90D0-C5CC255436E9",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Scheduled Start Time",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "57E4DDB1-71D4-4845-90D0-C5CC255436E9",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "57E4DDB1-71D4-4845-90D0-C5CC255436E9",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "57E4DDB1-71D4-4845-90D0-C5CC255436E9",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "57E4DDB1-71D4-4845-90D0-C5CC255436E9",
                    "sequence": 70,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Scheduled Start Time",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ScheduledStartTime",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "F9F78F53-FF18-40D1-842B-558A507BA699",
            "formelementid": "9AB1583B-8DA7-4B90-A0F7-5B6F8DD710EC",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Officer",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "9AB1583B-8DA7-4B90-A0F7-5B6F8DD710EC",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "9AB1583B-8DA7-4B90-A0F7-5B6F8DD710EC",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "9AB1583B-8DA7-4B90-A0F7-5B6F8DD710EC",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "9AB1583B-8DA7-4B90-A0F7-5B6F8DD710EC",
                    "sequence": 50,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Officer",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "OfficerName",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "2A9D3C04-A0FA-4E59-986A-A8236A0FEF21",
            "formelementid": "CEB8D30C-5D42-4495-8E07-3BBCE416BDE6",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Date",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "CEB8D30C-5D42-4495-8E07-3BBCE416BDE6",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "CEB8D30C-5D42-4495-8E07-3BBCE416BDE6",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "CEB8D30C-5D42-4495-8E07-3BBCE416BDE6",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "CEB8D30C-5D42-4495-8E07-3BBCE416BDE6",
                    "sequence": 60,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Date",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "StartDate",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "F04E5315-8FD7-441B-90AF-B1EF90316A90",
            "formelementid": "CF2B5116-067A-4CD5-B251-973C7A46C216",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Paid Hours",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "CF2B5116-067A-4CD5-B251-973C7A46C216",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "CF2B5116-067A-4CD5-B251-973C7A46C216",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "CF2B5116-067A-4CD5-B251-973C7A46C216",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "CF2B5116-067A-4CD5-B251-973C7A46C216",
                    "sequence": 110,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Paid Hours",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "PaidHours",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "44051B3F-F127-40E0-8AC7-DC896654562E",
            "formelementid": "855B4EB5-CFC9-4C2D-86AB-28A33D5E7EC4",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Flag Reason",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "855B4EB5-CFC9-4C2D-86AB-28A33D5E7EC4",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "855B4EB5-CFC9-4C2D-86AB-28A33D5E7EC4",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "855B4EB5-CFC9-4C2D-86AB-28A33D5E7EC4",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "855B4EB5-CFC9-4C2D-86AB-28A33D5E7EC4",
                    "sequence": 120,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Flag Reason",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "FlagReason",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "AFAED15E-EB30-4D24-B39D-DDE7F4ACE37A",
            "formelementid": "6A959D93-1EE0-4DB0-8DBC-2AC19938173B",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Employer",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "6A959D93-1EE0-4DB0-8DBC-2AC19938173B",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "6A959D93-1EE0-4DB0-8DBC-2AC19938173B",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "6A959D93-1EE0-4DB0-8DBC-2AC19938173B",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "6A959D93-1EE0-4DB0-8DBC-2AC19938173B",
                    "sequence": 30,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Employer",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Employer",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "23B6E849-4B36-4C13-BC48-E34A95D37F45",
            "formelementid": "CC8464EF-0C90-4677-AA63-4ED962340323",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Department",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "CC8464EF-0C90-4677-AA63-4ED962340323",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "CC8464EF-0C90-4677-AA63-4ED962340323",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "CC8464EF-0C90-4677-AA63-4ED962340323",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "CC8464EF-0C90-4677-AA63-4ED962340323",
                    "sequence": 20,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Department",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Department",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "A232C55F-54F5-4788-9F39-E9C5EAF7126C",
            "formelementid": "1E356547-0C20-43BF-8723-64473DA8CD9D",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Actual Start Time",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "1E356547-0C20-43BF-8723-64473DA8CD9D",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "1E356547-0C20-43BF-8723-64473DA8CD9D",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "1E356547-0C20-43BF-8723-64473DA8CD9D",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "1E356547-0C20-43BF-8723-64473DA8CD9D",
                    "sequence": 90,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Actual Start Time",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ActualStartTime",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "EDC19B8E-77FA-424A-8BD5-ED8194C691DB",
            "formelementid": "07CB0646-8282-4BE2-A8A7-0B0616638BC8",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Scheduled End Time",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "07CB0646-8282-4BE2-A8A7-0B0616638BC8",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "07CB0646-8282-4BE2-A8A7-0B0616638BC8",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "07CB0646-8282-4BE2-A8A7-0B0616638BC8",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "07CB0646-8282-4BE2-A8A7-0B0616638BC8",
                    "sequence": 80,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Scheduled End Time",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "ScheduledEndTime",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        },
        {
            "crudcolumnid": "274856D4-B837-450C-9FB1-F20401767872",
            "formelementid": "D42C8D3E-38DF-4B91-B72D-FD8897398482",
            "crudid": "A622DDC0-EF3B-4ECA-81EC-F126C6B223FD",
            "label": "Location",
            "iscolumn": 1,
            "isfilter": 1,
            "nextstructtype": "Step",
            "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDListIDs] @WorkflowID = '%v', @StepID = '%v'",
            "parentobjname": "crud",
            "childobjname": "crudcolumn",
            "parentid": "crudid",
            "childid": "crudid",
            "crudlistids": [
                {
                    "crudlistid": "4C32BD11-43F2-49ED-AEEF-40F4910463ED",
                    "formelementid": "D42C8D3E-38DF-4B91-B72D-FD8897398482",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "C8F35ABC-35F1-4E65-AF73-817865EA7A51",
                    "formelementid": "D42C8D3E-38DF-4B91-B72D-FD8897398482",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                },
                {
                    "crudlistid": "739A9F0A-3DB3-4E8E-97E3-C92706428FC3",
                    "formelementid": "D42C8D3E-38DF-4B91-B72D-FD8897398482",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDColumn_CRUDFormElement] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "crudlistids",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ],
            "formelement": [
                {
                    "formelementid": "D42C8D3E-38DF-4B91-B72D-FD8897398482",
                    "sequence": 200,
                    "selectoptions": "",
                    "required": 0,
                    "label": "Location",
                    "validminimum": 0,
                    "validmaximum": 100,
                    "masktype": "",
                    "datatype": "string",
                    "canedit": 0,
                    "allowmultiplepicklistselections": 0,
                    "paramname": "Location",
                    "nextstructtype": "StepWithAgency",
                    "nextsp": "exec [spxd_CRUD_Get_DetailReview_CRUDList_CRUDListItems_Unreviewed] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
                    "parentobjname": "crudcolumn",
                    "childobjname": "formelement",
                    "parentid": "formelementid",
                    "childid": "formelementid"
                }
            ]
        }
    ]
}
