export let submit_feedback_sept10 = [
    {
        "formid": "C65731B5-AD79-456F-B5B6-CDBD01BA8A25",
        "formelementid": "806BB697-DDD2-4A6F-9B2A-83C0BD19A4E7",
        "label": "Feedback Type",
        "sequence": 1,
        "advancedsetting": 0,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 0,
        "masktype": "",
        "datatype": "picklist",
        "canedit": 1,
        "required": 1,
        "groupid": "",
        "allowmultiplepicklistselections": 0,
        "saveparam": "FeedbackTypeID",
        "nextstructtype": "Step",
        "nextsp": "exec [spxd_Form_Get_SubmitFeedback_FormElements_SelectOptions] @WorkflowID = '%v', @StepID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": [
            {
                "id": "8c5e5ce3-302c-4eb2-87f5-bd05ffdc13ad",
                "label": "I encountered an error",
                "flag": "",
                "formelementid": "806BB697-DDD2-4A6F-9B2A-83C0BD19A4E7",
                "nextstructtype": "StepWithAgency",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "01ce997e-3ed1-4d12-b5bc-24a9f96e1780",
                "label": "I have feedback",
                "flag": "",
                "formelementid": "806BB697-DDD2-4A6F-9B2A-83C0BD19A4E7",
                "nextstructtype": "StepWithAgency",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            }
        ]
    },
    {
        "formid": "C65731B5-AD79-456F-B5B6-CDBD01BA8A25",
        "formelementid": "E8A057D4-CCA8-46AD-B2E2-C624B59011CD",
        "label": "Subject",
        "sequence": 2,
        "advancedsetting": 0,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 300,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "groupid": "",
        "allowmultiplepicklistselections": 0,
        "saveparam": "Subject",
        "nextstructtype": "Step",
        "nextsp": "exec [spxd_Form_Get_SubmitFeedback_FormElements_SelectOptions] @WorkflowID = '%v', @StepID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "C65731B5-AD79-456F-B5B6-CDBD01BA8A25",
        "formelementid": "97549246-D659-4BF3-AF9F-CFD450F4DAE2",
        "label": "Body",
        "sequence": 3,
        "advancedsetting": 0,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 300,
        "masktype": "textarea",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "groupid": "",
        "allowmultiplepicklistselections": 0,
        "saveparam": "Body",
        "nextstructtype": "Step",
        "nextsp": "exec [spxd_Form_Get_SubmitFeedback_FormElements_SelectOptions] @WorkflowID = '%v', @StepID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    }
]