export const formSBTstartandenddate = [
    {
      stepid: 'E47C64B1-0E36-4808-9FFC-33E89EC0E330',
      crudid: 'D1FBDF05-0CB3-41BD-9EB0-669B16D04C17',
      crudname: 'Details CRUD',
      reviewrequired: 0,
      formelementid: '1BCC7D71-19FB-407D-80C7-D3A9414DF6A5',
      sequence: 0,
      selectoptions: '',
      defaultvalue: '2024-04-28T18:19:41.93Z',
      required: 0,
      label: 'Start Date',
      validminimum: 0,
      validmaximum: 1000,
      masktype: 'date',
      datatype: 'datetime',
      canedit: 1,
      allowmultiplepicklistselections: 0,
      paramname: 'StartDate',
      isinput: 1,
      requiredbystep: 'E47C64B1-0E36-4808-9FFC-33E89EC0E330',
      currentstepid: '',
      navigationid: '',
      checkformelementid: '',
      validationrequired: 0,
      runsaveproc: 0,
      priority: 0,
      apicall: 0,
      apicallwithstep: 0,
      nextstructtype: 'StepWithAgency',
      nextsp:
        "exec [spxd_CRUD_Get_Details_CRUDList] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
      parentobjname: 'crud',
      childobjname: 'formelements',
      parentid: 'crudid',
      childid: 'crudid'
    },
    {
      stepid: 'E47C64B1-0E36-4808-9FFC-33E89EC0E330',
      crudid: 'D1FBDF05-0CB3-41BD-9EB0-669B16D04C17',
      crudname: 'Details CRUD',
      reviewrequired: 0,
      formelementid: 'D9B11214-22FC-4131-881E-D223FA8A002E',
      sequence: 1,
      selectoptions: '',
      defaultvalue: '2025-02-05T18:19:41.93Z',
      required: 0,
      label: 'End Date',
      validminimum: 0,
      validmaximum: 1000,
      masktype: 'date',
      datatype: 'datetime',
      canedit: 1,
      allowmultiplepicklistselections: 0,
      paramname: 'EndDate',
      isinput: 1,
      requiredbystep: 'E47C64B1-0E36-4808-9FFC-33E89EC0E330',
      currentstepid: '',
      navigationid: '',
      checkformelementid: '',
      validationrequired: 0,
      runsaveproc: 0,
      priority: 0,
      apicall: 0,
      apicallwithstep: 0,
      nextstructtype: 'StepWithAgency',
      nextsp:
        "exec [spxd_CRUD_Get_Details_CRUDList] @WorkflowID = '%v', @StepID = '%v', @AgencyID = '%v'",
      parentobjname: 'crud',
      childobjname: 'formelements',
      parentid: 'crudid',
      childid: 'crudid'
    }
  ]