export const formtestingdatefuncs = [
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "B43E2E6C-0FC2-4950-8C44-4BBC6834F51F",
    //     "label": "placeholder FormElement",
    //     "sequence": 0,
    //     "defaultvalue": "",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "",
    //     "datatype": "string",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "placeholderFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "",
    //     "fieldname": "",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "5DBEBA7B-365A-486A-A112-236061699348",
    //     "label": "TestID",
    //     "sequence": 1,
    //     "defaultvalue": "TestPassingID",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "",
    //     "datatype": "string",
    //     "canedit": 0,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "TestID",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "E3288BFB-1533-4CBE-A8B9-EBE338D58B59",
    //     "fieldname": "TestID",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "1DECD917-A71D-46BC-819C-F1966DC2B581",
    //     "label": "TextArea FormElement",
    //     "sequence": 2,
    //     "defaultvalue": "Remove 'textarea' masktype for regular text field",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "textarea",
    //     "datatype": "string",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "TextAreaFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "",
    //     "fieldname": "",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "E5D59C99-1B0B-4373-A2F0-2858B21E5EFA",
    //     "label": "email FormElement",
    //     "sequence": 3,
    //     "defaultvalue": "",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "email",
    //     "datatype": "string",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "EmailFieldFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "",
    //     "fieldname": "",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "86F5AD89-593A-4446-B07F-706BAB0A1EE6",
    //     "label": "phone FormElement",
    //     "sequence": 4,
    //     "defaultvalue": "",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "phone",
    //     "datatype": "string",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "PhoneFieldFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "",
    //     "fieldname": "",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "ACEED14C-146A-47C3-8DCE-7D6D9E4F88FE",
    //     "label": "integer FormElement limit by 0 <= x <= 100",
    //     "sequence": 5,
    //     "defaultvalue": "",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "",
    //     "datatype": "int",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "integerFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "",
    //     "fieldname": "",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "EA705A4D-EB07-42D1-9CAC-7B86288AB266",
    //     "label": "float FormElement limit by 0 <= x <= 100",
    //     "sequence": 6,
    //     "defaultvalue": "",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "",
    //     "datatype": "float",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "floatFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "",
    //     "fieldname": "",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "41BF19FF-57CB-4FDA-A90C-1B86C7C80FBD",
    //     "label": "password FormElement",
    //     "sequence": 7,
    //     "defaultvalue": "",
    //     "validminimum": 8,
    //     "validmaximum": 16,
    //     "masktype": "password",
    //     "datatype": "string",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "passwordFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "",
    //     "fieldname": "",
    //     "hash": "$1u9C#h@E5fR6Tz0mPqNlOoDp2Qw3Xs4Vc5Fg6B",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // },
    {
        "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
        "formelementid": "9B151438-052D-4140-8959-7E95E46AC33D",
        "label": "date FormElement",
        "sequence": 8,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 100,
        "masktype": "date",
        "datatype": "datetime",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "saveparam": "DateFE",
        "groupid": "",
        "hidden": 0,
        "format": "",
        "requiredbystep": "",
        "fieldname": "",
        "hash": "",
        "nextstructtype": "",
        "nextsp": "",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid"
    },
    {
        "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
        "formelementid": "F3C451FC-1662-4E5C-A40F-B9D1A5B5A5FE",
        "label": "time FormElement",
        "sequence": 9,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 100,
        "masktype": "time",
        "datatype": "datetime",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "saveparam": "timeFE",
        "groupid": "",
        "hidden": 0,
        "format": "",
        "requiredbystep": "",
        "fieldname": "",
        "hash": "",
        "nextstructtype": "",
        "nextsp": "",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid"
    },
    {
        "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
        "formelementid": "FA8948FF-5667-4B38-87E8-F5B376AFFA01",
        "label": "datetime FormElement",
        "sequence": 10,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 100,
        "masktype": "",
        "datatype": "datetime",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "saveparam": "datetimeFE",
        "groupid": "",
        "hidden": 0,
        "format": "",
        "requiredbystep": "",
        "fieldname": "",
        "hash": "",
        "nextstructtype": "",
        "nextsp": "",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid"
    },
    {
        "formid": "E20CED9asds5-0B8F-4EF8-85A4-C6F8CAEBA867",
        "formelementid": "AAAAAA-5667-4B38-87E8-F5B376AFFA01",
        "label": "default datetime FormElement",
        "sequence": 10,
        "defaultvalue": "2027-11-06T10:30:00.000Z",
        "validminimum": 1,
        "validmaximum": 100,
        "masktype": "",
        "datatype": "datetime",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "saveparam": "datetimeFE",
        "groupid": "",
        "hidden": 0,
        "format": "",
        "requiredbystep": "",
        "fieldname": "",
        "hash": "",
        "nextstructtype": "",
        "nextsp": "",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "id": "sdfdfd-5667-4B38-87E8-F5B376AFFA01",
        "remainingRequirements": [],
        // "value": "2027-11-06T10:30:00.000Z",
        "isEdit": true,
        "isReview": false
    }
    // {
    //     "formid": "E20CED95-0B8F-4EF8-85A4-C6F8CAEBA867",
    //     "formelementid": "DE48C4FE-89AC-45AE-AD4B-E64DCF245091",
    //     "label": "datelist FormElement",
    //     "sequence": 13,
    //     "defaultvalue": "",
    //     "validminimum": 1,
    //     "validmaximum": 100,
    //     "masktype": "datetime",
    //     "datatype": "datelist",
    //     "canedit": 1,
    //     "required": 0,
    //     "allowmultiplepicklistselections": 0,
    //     "saveparam": "DatelistFE",
    //     "groupid": "",
    //     "hidden": 0,
    //     "format": "",
    //     "requiredbystep": "E3288BFB-1533-4CBE-A8B9-EBE338D58B59",
    //     "fieldname": "DatelistFE",
    //     "hash": "",
    //     "nextstructtype": "",
    //     "nextsp": "",
    //     "parentobjname": "form",
    //     "childobjname": "formelements",
    //     "parentid": "formid",
    //     "childid": "formid"
    // }
]