export const formerequestadetail = [
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "66E7B2F3-0961-41FB-849E-BB6B66911D46",
        "label": "",
        "sequence": 0,
        "defaultvalue": "",
        // "validminimum": 1,
        // "validmaximum": 5000,
        "mincharacters": 1,
        "maxcharacters": 5000,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "DynamicFormElementV",
        "format": "",
        "link": "",
        "islink": 1,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "9517DF24-BDC8-4EEC-809A-D12C5BA11CBD",
        "label": "Please enter the contact information for the person who will be responsible for this detail.",
        "sequence": 0,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "contact",
        "hidden": 0,
        "saveparam": "ContactDescription",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "7404B1F9-3DE3-4A6E-A111-C432018E5AAF",
        "label": "Rate",
        "sequence": 1,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 250,
        "mincharacters": 1,
        "maxcharacters": 250,
        "masktype": "query",
        "datatype": "picklist",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "QuestionOne",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": [
            {
                "id": "Tier 1 - $43.12/hr",
                "label": "Tier 1 - $43.12/hr",
                "flag": "",
                "formelementid": "7404B1F9-3DE3-4A6E-A111-C432018E5AAF",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "Tier 2 - $62.16/hr (most common rate)",
                "label": "Tier 2 - $62.16/hr (most common rate)",
                "flag": "",
                "formelementid": "7404B1F9-3DE3-4A6E-A111-C432018E5AAF",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "Tier 3 - $73.36/hr",
                "label": "Tier 3 - $73.36/hr",
                "flag": "",
                "formelementid": "7404B1F9-3DE3-4A6E-A111-C432018E5AAF",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "Tier 4 - Supervisor - $78.96/hr",
                "label": "Tier 4 - Supervisor - $78.96/hr",
                "flag": "",
                "formelementid": "7404B1F9-3DE3-4A6E-A111-C432018E5AAF",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "Tier 5 - Less than 48 hours notice / Holidays - $90.16/hr",
                "label": "Tier 5 - Less than 48 hours notice / Holidays - $90.16/hr",
                "flag": "",
                "formelementid": "7404B1F9-3DE3-4A6E-A111-C432018E5AAF",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "Tier 6 - Less than 48 hours notice-Supervisor / Holidays-Supervisor - $101.36/hr",
                "label": "Tier 6 - Less than 48 hours notice-Supervisor / Holidays-Supervisor - $101.36/hr",
                "flag": "",
                "formelementid": "7404B1F9-3DE3-4A6E-A111-C432018E5AAF",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            }
        ]
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "67307140-0A08-45A5-BD47-0682A302B1B3",
        "label": "Type of Request",
        "sequence": 1,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 200,
        "mincharacters": 1,
        "maxcharacters": 200,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail information",
        "hidden": 1,
        "saveparam": "TypeOfRequest",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "03F67AC1-B3B4-4630-ADD0-2A45B3EB7D83",
        "label": "Contact Name",
        "sequence": 1,
        "defaultvalue": "Priyanka Patel",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "contact",
        "hidden": 0,
        "saveparam": "ContactName",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "4B4044C6-5D3A-44F1-A18A-9DE86982BA0E",
        "label": "Address 1",
        "sequence": 1,
        "defaultvalue": "Jivasoft",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail location",
        "hidden": 0,
        "saveparam": "LocationAddress",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "Address 1 (and cross street if applicable)",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "B7C6E0FB-F540-470A-AB1E-5B824318E531",
        "label": "Customer's date of birth (required by JSO): mm/dd/yyyy",
        "sequence": 2,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 250,
        "mincharacters": 1,
        "maxcharacters": 250,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "QuestionTwo",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "5A4F593F-4EF0-46DF-AD27-6A0D4FAD2427",
        "label": "Detail Description",
        "sequence": 2,
        "defaultvalue": "Dev test",
        "validminimum": 1,
        "validmaximum": 1000,
        "mincharacters": 1,
        "maxcharacters": 1000,
        "masktype": "textarea",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail information",
        "hidden": 0,
        "saveparam": "DetailDescription",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "453AF406-C34E-4D02-A1E3-DC2E376431CD",
        "label": "Phone Number",
        "sequence": 2,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "phone",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "contact",
        "hidden": 0,
        "saveparam": "ContactPhone",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "6E8F30C6-8EAB-4245-B71E-F57EC0E644E7",
        "label": "Address 2",
        "sequence": 2,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 0,
        "mincharacters": 0,
        "maxcharacters": 0,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail location",
        "hidden": 0,
        "saveparam": "LocationAddressII",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "AB019598-AB81-4F2F-98B3-7FCEB4466A99",
        "label": "How many people are expected at your event?",
        "sequence": 3,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 250,
        "mincharacters": 1,
        "maxcharacters": 250,
        "masktype": "",
        "datatype": "number",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "QuestionThree",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "0A728D7D-7BF1-4D2A-B309-14BFEAC7CC04",
        "label": "Email",
        "sequence": 3,
        "defaultvalue": "priyanka.patel@jivasoft.com",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "email",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "contact",
        "hidden": 0,
        "saveparam": "ContactEmail",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "1A617133-207B-4137-AA9F-7818067E6823",
        "label": "Number of Officers",
        "sequence": 3,
        "defaultvalue": "1",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "",
        "datatype": "int",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail information",
        "hidden": 0,
        "saveparam": "DetailOfficerNum",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "7D58CC79-F54E-4123-BD9E-8003BD3D8FBE",
        "label": "City",
        "sequence": 3,
        "defaultvalue": "San Antonio",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 0,
        "maxcharacters": 0,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail location",
        "hidden": 0,
        "saveparam": "LocationCity",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "ED925016-D15B-4E30-9A72-D1AE37A8E0BA",
        "label": "Is this request for a special event that requires a city permit? IE. Park permit, block party, street closure, festival, or other special event.",
        "sequence": 4,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 250,
        "mincharacters": 1,
        "maxcharacters": 250,
        "masktype": "query",
        "datatype": "picklist",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "QuestionFour",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": [
            {
                "id": "No",
                "label": "No",
                "flag": "",
                "formelementid": "ED925016-D15B-4E30-9A72-D1AE37A8E0BA",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "Yes",
                "label": "Yes",
                "flag": "",
                "formelementid": "ED925016-D15B-4E30-9A72-D1AE37A8E0BA",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            }
        ]
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
        "label": "State",
        "sequence": 4,
        "defaultvalue": "TX",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "query",
        "datatype": "picklist",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail location",
        "hidden": 0,
        "saveparam": "LocationState",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": [
            {
                "id": "AL",
                "label": "Alabama",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "AK",
                "label": "Alaska",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "AB",
                "label": "Alberta",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "AS",
                "label": "American Samoa",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "AZ",
                "label": "Arizona",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "AR",
                "label": "Arkansas",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "BC",
                "label": "British Columbia",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CA",
                "label": "California",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CO",
                "label": "Colorado",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CT",
                "label": "Connecticut",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CO",
                "label": "Delaware",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "DC",
                "label": "District of Columbia",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "FM",
                "label": "Federated States of Micronesia",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "FL",
                "label": "Florida",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "GA",
                "label": "Georgia",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "GU",
                "label": "Guam",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "HI",
                "label": "Hawaii",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "ID",
                "label": "Idaho",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "IL",
                "label": "Illinois",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "IN",
                "label": "Indiana",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "IA",
                "label": "Iowa",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "KS",
                "label": "Kansas",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "KY",
                "label": "Kentucky",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "LA",
                "label": "Louisiana",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "ME",
                "label": "Maine",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MB",
                "label": "Manitoba",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MH",
                "label": "Marshall Islands",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MD",
                "label": "Maryland",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MA",
                "label": "Massachusetts",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MI",
                "label": "Michigan",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MN",
                "label": "Minnesota",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MS",
                "label": "Mississippi",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MO",
                "label": "Missouri",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MT",
                "label": "Montana",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NE",
                "label": "Nebraska",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NV",
                "label": "Nevada",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NB",
                "label": "New Brunswick",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NH",
                "label": "New Hampshire",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NJ",
                "label": "New Jersey",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NM",
                "label": "New Mexico",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NY",
                "label": "New York",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NL",
                "label": "Newfoundland and Labrador",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NC",
                "label": "North Carolina",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "ND",
                "label": "North Dakota",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "MP",
                "label": "Northern Mariana Islands",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NT",
                "label": "Northwest Territories",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NS",
                "label": "Nova Scotia",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "NU",
                "label": "Nunavut",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "OH",
                "label": "Ohio",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "OK",
                "label": "Oklahoma",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "ON",
                "label": "Ontario",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "OR",
                "label": "Oregon",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "PW",
                "label": "Palau",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "PA",
                "label": "Pennsylvania",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "PE",
                "label": "Prince Edward Island",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "PR",
                "label": "Puerto Rico",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "QC",
                "label": "Quebec",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "RI",
                "label": "Rhode Island",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "SK",
                "label": "Saskatchewan",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "SC",
                "label": "South Carolina",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "SD",
                "label": "South Dakota",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "TN",
                "label": "Tennessee",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "TX",
                "label": "Texas",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "UT",
                "label": "Utah",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "VT",
                "label": "Vermont",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "VI",
                "label": "Virgin Islands",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "VA",
                "label": "Virginia",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "WA",
                "label": "Washington",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "WV",
                "label": "West Virginia",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "WI",
                "label": "Wisconsin",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "WY",
                "label": "Wyoming",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "YT",
                "label": "Yukon",
                "flag": "",
                "formelementid": "9F1A6AAC-6998-4395-A353-5853A6CF61AB",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            }
        ]
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "DD07F4FB-300C-4460-A85E-90533717FF68",
        "label": "Is a patrol car required to perform this detail?",
        "sequence": 4,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "",
        "datatype": "checkbox",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail information",
        "hidden": 1,
        "saveparam": "DetailVehicle",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "C0B93802-8A25-4BC2-BBDF-715DECA9EFEC",
        "label": "Will alcohol be served during your event?",
        "sequence": 5,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 250,
        "mincharacters": 1,
        "maxcharacters": 250,
        "masktype": "query",
        "datatype": "picklist",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "QuestionFive",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": [
            {
                "id": " Yes",
                "label": " Yes",
                "flag": "",
                "formelementid": "C0B93802-8A25-4BC2-BBDF-715DECA9EFEC",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "No",
                "label": "No",
                "flag": "",
                "formelementid": "C0B93802-8A25-4BC2-BBDF-715DECA9EFEC",
                "nextstructtype": "StepWithSoftwareUserAndAgency",
                "nextsp": "exec [spxd_Form_Get_Detail_Request_Group] @WorkflowID = '%v', @StepID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            }
        ]
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "8C7AB2E2-F5C0-4A5A-B215-7968BCDC8722",
        "label": "Zipcode",
        "sequence": 5,
        "defaultvalue": "12345",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail location",
        "hidden": 0,
        "saveparam": "LocationZip",
        "format": "#####",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "43D1DCBC-1B47-4A86-9BF7-85FD718D216F",
        "label": "Start And End Date/Time",
        "sequence": 5,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 100,
        "mincharacters": 1,
        "maxcharacters": 100,
        "masktype": "datetime",
        "datatype": "datelist",
        "canedit": 1,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "groupid": "Schedule",
        "hidden": 0,
        "saveparam": "DetailDateList",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 15,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "59F1BE46-AEFD-403E-A8D6-DB10887C4CF8",
        "label": "Note to pass along to the Officer",
        "sequence": 6,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 1000,
        "mincharacters": 0,
        "maxcharacters": 1000,
        "masktype": "textarea",
        "datatype": "string",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail information",
        "hidden": 0,
        "saveparam": "DetailNote",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "18EC9CE6-9CB4-4962-BDEE-E7CFE49C4385",
        "label": "Optional - Location Description",
        "sequence": 6,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 1000,
        "mincharacters": 1,
        "maxcharacters": 1000,
        "masktype": "textarea",
        "datatype": "string",
        "canedit": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "detail location",
        "hidden": 0,
        "saveparam": "LocationDescription",
        "format": "",
        "link": "",
        "islink": 0,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "BD819105-A9E0-4D3B-98BD-03AE7D73C2D0",
        "label": "",
        "sequence": 101,
        "defaultvalue": "Community Centers and Parks",
        "validminimum": 1,
        "validmaximum": 5000,
        "mincharacters": 1,
        "maxcharacters": 5000,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "DynamicFormElementI",
        "format": "",
        "link": "https://urldefense.proofpoint.com/v2/url?u=https-3A__web1.myvscloud.com_wbwsc_fljacksonwt.wsc_splash.html&d=DwMFAg&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=pftSudo8war-UOBNXiQsyXsRXwbJfN4xaxyOeKUMGa8&m=rmTt5KcMCnfhHsqiNvGoE9Wwz7v_aEeWfNCZSzaDg7feOvyvkYiSbjgogYFuQJ45&s=T28OOrz0zmDNILfZz0dfkfWMTfPNNhBAumLHUbdFbjM&e=",
        "islink": 1,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "A93F0311-2A8E-4A60-ABDD-219C34C6A32C",
        "label": "",
        "sequence": 102,
        "defaultvalue": "General Permits",
        "validminimum": 1,
        "validmaximum": 5000,
        "mincharacters": 1,
        "maxcharacters": 5000,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "DynamicFormElementII",
        "format": "",
        "link": "https://urldefense.proofpoint.com/v2/url?u=https-3A__specialevents.coj.net_Permitting_About-2DPermitting.aspx&d=DwMFAg&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=pftSudo8war-UOBNXiQsyXsRXwbJfN4xaxyOeKUMGa8&m=rmTt5KcMCnfhHsqiNvGoE9Wwz7v_aEeWfNCZSzaDg7feOvyvkYiSbjgogYFuQJ45&s=sv9QoHcghuduCeeBwILl4DvAgLWGp6B6f-Ogpfdea9E&e=",
        "islink": 1,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "65DEA328-9410-4CEC-9510-4347F7BBFCEF",
        "label": "",
        "sequence": 103,
        "defaultvalue": "Apply for permit",
        "validminimum": 1,
        "validmaximum": 5000,
        "mincharacters": 1,
        "maxcharacters": 5000,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "DynamicFormElementIII",
        "format": "",
        "link": "https://urldefense.proofpoint.com/v2/url?u=https-3A__specialevents.coj.net_Permitting_Apply-2Dfor-2Da-2DPermit.aspx&d=DwMFAg&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=pftSudo8war-UOBNXiQsyXsRXwbJfN4xaxyOeKUMGa8&m=rmTt5KcMCnfhHsqiNvGoE9Wwz7v_aEeWfNCZSzaDg7feOvyvkYiSbjgogYFuQJ45&s=hQ0wHZQ0t5lJvAT9xCfxh4L-ayN0T6jkmGYAtEO3qcw&e=",
        "islink": 1,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "3C4FEE73-3F3E-4C25-A9DB-91E32101D3ED",
        "formelementid": "75643C4A-FE1A-4F2F-AEDD-F6A9BC9ECBD0",
        "label": "",
        "sequence": 104,
        "defaultvalue": "Please call the Special Events Office at 904-630-1953 with questions regarding the permitting process.",
        "validminimum": 1,
        "validmaximum": 5000,
        "mincharacters": 1,
        "maxcharacters": 5000,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "groupid": "additional information",
        "hidden": 0,
        "saveparam": "DynamicFormElementIV",
        "format": "",
        "link": "",
        "islink": 1,
        "interval": 0,
        "placeholder": "",
        "nextstructtype": "StepWithSoftwareUserAndAgency",
        "nextsp": "exec [spxd_Form_Get_Detail_Request_FormElements_SelectOptions]@WorkflowID = '%v', @SoftwareUserID = '%v', @AgencyID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    }
]