export const form_formelements_testingdata = [
    {
        "formid": "01AE2C85-C947-4A9B-B6B4-6AB1D11E1997",
        "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
        "label": "State",
        "sequence": 10,
        "defaultvalue": "",
        "validminimum": 1,
        "validmaximum": 1,
        "masktype": "query",
        "datatype": "picklist",
        "canedit": 1,
        "format": "",
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingStateRegistration",
        "groupid": "Billing",
        "hidden": 0,
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerRegistration_FormElements_SelectOptions]",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": [
            {
                "id": "4DDA9CEE-51DB-411C-A191-018508E8F2F3",
                "label": "Alabama",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "937418D7-F439-43D2-AAE6-641FE9B05F12",
                "label": "Alaska",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "74BAAE69-C0C0-422E-9164-6D12F56B8533",
                "label": "Alberta",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "45A08459-A360-4B20-9481-99D8CC7E5194",
                "label": "American Samoa",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "F4B552B4-C964-4CFD-902F-1381DF154E6B",
                "label": "Arizona",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "8BCC7A35-9C1E-4BC1-A9A9-B3A507E74443",
                "label": "Arkansas",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "9E03CFAC-8095-40B9-B3DA-E4FABF2925C0",
                "label": "British Columbia",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "FD6590FB-766A-4A7D-BB71-34C92994F619",
                "label": "California",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "637733E5-111B-4F6F-8FF4-FF31521D8553",
                "label": "Colorado",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E75E18AE-022B-4767-9E78-645B476144CA",
                "label": "Connecticut",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A36AA15C-F86C-42B5-96CF-E5C255A99227",
                "label": "Delaware",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "5DBB166C-8CB7-4F2E-84C9-E7B2CD9E6832",
                "label": "District of Columbia",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "6EFE6D6C-6A44-4557-A6FB-8F9B38640CE7",
                "label": "Federated States of Micronesia",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E544DCA7-D87C-434E-8E99-730FFD731A89",
                "label": "Florida",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "8C8390F9-D425-4F6A-BA2C-6BDBE3CA4ABC",
                "label": "Georgia",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "6877AAB8-B70C-44AB-AE71-82E78EA53789",
                "label": "Guam",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "296CC859-8CD8-425B-9A0B-0B01E9327F81",
                "label": "Hawaii",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "4D18A00B-42E6-4EAB-A15D-C999BEE570DC",
                "label": "Idaho",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "6FDDFEC9-67AF-4BE5-BA3A-38A5601B8B0C",
                "label": "Illinois",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "6F1ED1A7-C00B-44CF-90D5-8C4249DB3B64",
                "label": "Indiana",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "FB7EAA45-0389-4DD9-BC78-5708F7CEA6EA",
                "label": "Iowa",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "C4B1A61D-9171-4313-BA82-CA5014D074C0",
                "label": "Kansas",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A649ABF1-0FE5-4AFE-B02C-C665F06C6413",
                "label": "Kentucky",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "4BD3B018-2F81-4EF3-B23A-5F32B6FEAC33",
                "label": "Louisiana",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D4DAA3CB-1F59-441B-A882-867D274403CB",
                "label": "Maine",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "61E8571B-0483-4324-8920-A3F0C7592BE3",
                "label": "Manitoba",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0D81489F-EEC6-43E0-A81C-FC8D3CE16161",
                "label": "Marshall Islands",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E029B297-5152-4DC4-964D-3C3E2DB35A8B",
                "label": "Maryland",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "99DC930D-6A8B-4434-9D82-F34DB715F745",
                "label": "Massachusetts",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "13443F16-91AD-4BE4-95FD-F3AE4103406E",
                "label": "Michigan",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "5AD87740-F272-473D-8F89-2432481A829F",
                "label": "Minnesota",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "4ED8219C-E0E5-4CF2-865D-1512CF15D810",
                "label": "Mississippi",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "DD361CF6-DB93-4C1E-B518-0E3D359BD796",
                "label": "Missouri",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "80D39924-C74C-4CFB-9FB0-1F176A73F262",
                "label": "Montana",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3D8D4355-77F3-4C0A-B1A6-7A70CBE6F9BF",
                "label": "Nebraska",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E0B2B457-8B77-4DFC-84D4-CCAC73FCA5AB",
                "label": "Nevada",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CC3A9D9E-3F36-45DD-B12C-B85797F07B17",
                "label": "New Brunswick",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A286C815-30C6-4418-A395-925C4D2B2D20",
                "label": "New Hampshire",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0E910401-2D8B-4EAE-82CF-450547E86881",
                "label": "New Jersey",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "38B2975A-61A8-4563-AF71-87E59199BFA9",
                "label": "New Mexico",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0298A2A4-86BB-48F6-B078-F3740434B9C3",
                "label": "New York",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "188A17B7-CD34-4DD8-9D68-66F466D9926F",
                "label": "Newfoundland and Labrador",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3EBBD027-5250-4D8D-B56B-D3616A0299D3",
                "label": "North Carolina",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E7B8BBB5-08E5-4BA9-BFC4-564D7827682D",
                "label": "North Dakota",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "5E437E46-D172-4872-A405-C89ECC71B235",
                "label": "Northern Mariana Islands",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "95C02000-97A6-4375-8F10-8A619BFCE6E7",
                "label": "Northwest Territories",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "F272B767-597E-4684-AAE1-545AB9DFED08",
                "label": "Nova Scotia",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "25F1BCD6-73FC-4ECF-812D-8799A73FDD6C",
                "label": "Nunavut",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "C04352B2-EB99-4116-B9EA-F74BC31D65E3",
                "label": "Ohio",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "2B026FC6-E5F0-4DB5-9704-3910FFCEDE80",
                "label": "Oklahoma",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "1513F029-BCAD-4372-AEB6-0E1184A49943",
                "label": "Ontario",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0CDFBDFC-9E6C-4C4B-ADA9-BA65F095CC0A",
                "label": "Oregon",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E515EBC0-BD3D-44A5-A921-97EF8E6E52F7",
                "label": "Palau",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "59321E45-ECCF-4E0D-B827-F7C563C26197",
                "label": "Pennsylvania",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "4EEDFDC9-C327-44C7-A7C9-4651695930ED",
                "label": "Prince Edward Island",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "11FECCD7-9380-4012-ADD1-F4505A86963F",
                "label": "Puerto Rico",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0C8AE714-73F6-453B-B0EC-7B5EB1AFAF16",
                "label": "Quebec",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "2C14738F-184E-454C-BB44-55185930F22B",
                "label": "Rhode Island",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "5E9AD714-91EF-4B8F-AF6D-0B6E4792AE53",
                "label": "Saskatchewan",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3E4D8DA3-1F47-49A3-9BAB-3E088A56350F",
                "label": "South Carolina",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "BE24FB70-4FCF-481D-B6ED-43C9746DFDC5",
                "label": "South Dakota",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "24EAEE63-C26A-4E02-B3E9-5F16C4253170",
                "label": "Tennessee",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "2D999EC9-C5D0-489D-A2B2-EEFCCE5651B2",
                "label": "Texas",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "2E6C2789-47F1-445D-840D-B840EC83AD4B",
                "label": "Utah",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D5A10CEF-E44F-4F14-AAEB-A25A4C870E45",
                "label": "Vermont",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0D645914-FA9A-4857-B7E9-727CD3529632",
                "label": "Virgin Islands",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "086A5AE2-96F5-4DE8-987E-B5FACA7E5ED2",
                "label": "Virginia",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "52576396-2DC5-4748-81EF-EC9284F98D9D",
                "label": "Washington",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "FC20013E-3513-41F3-9769-77CEACD0D6EA",
                "label": "West Virginia",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A70DACAD-EE0F-44D1-9ADC-39F3102ADB58",
                "label": "Wisconsin",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "9703818E-1D91-4191-923A-8DEBBF142EA8",
                "label": "Wyoming",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3058E4F0-598B-4559-B8A1-E168006183CB",
                "label": "Yukon",
                "flag": "",
                "formelementid": "A135869F-766D-442B-8346-8F9EF95BBEB3",
                "nextstructtype": "StepWithSoftwareUser",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            }
        ]
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "C4899493-1DA2-43D2-9E68-65BB16805EE7",
        "label": "Customer Name",
        "sequence": 1,
        "defaultvalue": "Greensboro Housing Authority Gateway Plaza",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "User Profile",
        "allowmultiplepicklistselections": 0,
        "saveparam": "CustomerNameProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "9B402AD9-4420-430A-B282-D791D0FC6B5C",
        "label": "First Name",
        "sequence": 2,
        "defaultvalue": "Darryl",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 0,
        "groupid": "User Profile",
        "allowmultiplepicklistselections": 0,
        "saveparam": "ContactFirstNameProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "A8A62EE9-75EC-40DB-B484-2565E8407D86",
        "label": "Last Name",
        "sequence": 3,
        "defaultvalue": "Stevenson",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "groupid": "User Profile",
        "allowmultiplepicklistselections": 0,
        "saveparam": "ContactLastNameProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "810A253A-412E-46C2-8692-45C0C1E9E34F",
        "label": "Phone Number",
        "sequence": 4,
        "defaultvalue": "3363242189",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "phone",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "groupid": "User Profile",
        "allowmultiplepicklistselections": 0,
        "saveparam": "ContactPhoneNumberProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "64E3B22B-6F18-49A0-A7C0-8B97FBFA64E7",
        "label": "Email",
        "sequence": 5,
        "defaultvalue": "dstevenson@greensboro-nc.gov",
        "validminimum": 1,
        "validmaximum": 128,
        "masktype": "email",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "User Profile",
        "allowmultiplepicklistselections": 0,
        "saveparam": "ContactEmailProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "4CD685FB-3FB3-4ACB-A16E-40145B86BB5A",
        "label": "First Name",
        "sequence": 8,
        "defaultvalue": "Darryl",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 0,
        "groupid": "Scheduling Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "SchedulingContactFirstNameProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "17603456-EDD3-46C7-9216-36C6A9C5BB6F",
        "label": "Last Name",
        "sequence": 9,
        "defaultvalue": "Stevenson",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "groupid": "Scheduling Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "SchedulingContactLastNameProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "24B4C854-FE35-4FE0-8771-A7A5FD182A45",
        "label": "Phone Number",
        "sequence": 10,
        "defaultvalue": "3363242189",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "phone",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "groupid": "Scheduling Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "SchedulingContactPhoneNumberProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "503F8691-84A3-4374-A729-1E9484DCD970",
        "label": "Email",
        "sequence": 11,
        "defaultvalue": "dstevenson@greensboro-nc.gov",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 1,
        "required": 1,
        "groupid": "Scheduling Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "SchedulingContactEmailProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "4D0C9C7A-01AC-4BF7-BF20-DD7FCF56D1A8",
        "label": "Note:",
        "sequence": 12,
        "defaultvalue": "Please email portal.feedback@extradutysolutions.com if any of the following information is incorrect.",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingContactNoteProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "69F19F8D-D5F1-49F0-B574-1A0EB0CADA96",
        "label": "First Name",
        "sequence": 13,
        "defaultvalue": "Darryl",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingContactFirstNameProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "7D75821B-8F50-47D0-8B7E-6B5F1F3D1BD6",
        "label": "Last Name",
        "sequence": 14,
        "defaultvalue": "Stevenson",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingContactLastNameProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "1E754170-49D5-4E8E-98EE-E7449EEF674C",
        "label": "Phone 1",
        "sequence": 15,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "phone",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingContactPhoneNumberProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "992BD64B-6204-4B0C-9953-87C335C7F6B6",
        "label": "Phone 2",
        "sequence": 16,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 100,
        "masktype": "phone",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingContactPhoneNumberTwoProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "0A1E2354-19F3-46B6-940E-154C21FCDDE1",
        "label": "Email",
        "sequence": 17,
        "defaultvalue": "dstevenson@greensboro-nc.gov",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingContactEmailProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "41A372C0-312F-42E6-9455-DFA4A8568A98",
        "label": "Address 1",
        "sequence": 18,
        "defaultvalue": "100 E. Police Plaza",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingAddressOneProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "7208EEA8-A888-4A4E-B1D4-D695999E3CAC",
        "label": "Address 2",
        "sequence": 19,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingAddressTwoProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "DC6EB2A4-36C4-43A9-8D88-AC82017BC5EA",
        "label": "City",
        "sequence": 20,
        "defaultvalue": "Greensboro",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingCityProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
        "label": "State",
        "sequence": 21,
        "defaultvalue": "D9E19436-5006-4BD9-B645-B57E1B44901E",
        "validminimum": 0,
        "validmaximum": 128,
        "masktype": "query",
        "datatype": "picklist",
        "canedit": 1,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingStateProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": [
            {
                "id": "7751526A-105C-49F5-81BA-E266E2865D68",
                "label": "Alabama",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D90BDC74-1F76-4D48-B3DA-45B3D0B88D1C",
                "label": "Alaska",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "650CB360-367D-4C0D-8D09-79E5DF4F6AA1",
                "label": "Alberta",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "C3D86576-1BA4-4797-954F-A00519F76D58",
                "label": "American Samoa",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D025DAD4-0093-4583-9321-6C3B93822F17",
                "label": "Arizona",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "C1F17535-3A01-4BC0-8D4B-51B466BD7C96",
                "label": "Arkansas",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "49C31139-6DB3-4255-849F-AF0E18A1BF81",
                "label": "British Columbia",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CFECA13F-261E-47D6-A1E7-D11F1333786E",
                "label": "California",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3145EDE0-531E-40D3-8B42-CE68E8EC9BD5",
                "label": "Colorado",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "10E97137-CCB1-45A2-8937-0CD33B8EDEAD",
                "label": "Connecticut",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "370DD836-C8F3-48F8-B2EA-ED3470DE2DA8",
                "label": "Delaware",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "63619C06-043D-49FE-94C0-1B386D4508E1",
                "label": "District Of Columbia",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D9BA62EC-7692-47BD-B818-09A32D9E5DEE",
                "label": "Federated States Of Micronesia",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "1013240C-BF0C-45AE-9BF4-ED30EBF2E756",
                "label": "Florida",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A78AF35D-004B-4457-995A-4CDA16575EC6",
                "label": "Georgia",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "680236F6-B661-4B40-9B0F-E5CFC51A390B",
                "label": "Guam",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "9A467A66-F21C-48C6-8B51-FC99809DCBEA",
                "label": "Hawaii",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "8C9ECC1E-B151-4C78-9453-EE61665B4110",
                "label": "Idaho",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A79986AC-4A62-41B5-8BEB-8C2545E5915A",
                "label": "Illinois",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A9E62EBE-09ED-4989-9468-5438B365E88F",
                "label": "Indiana",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "7796BD8A-043B-40B8-98AA-8978477C6920",
                "label": "Iowa",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "F73073B3-7908-4182-BB6D-393E2D30B697",
                "label": "Kansas",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CD7D18F0-8952-4CBE-AD15-50D57CC9183C",
                "label": "Kentucky",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3465CFD4-FC5B-4AA2-B3DA-706BB8013869",
                "label": "Louisiana",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "11BF161B-6A0B-4E9C-B497-2836D69FB093",
                "label": "Maine",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "6EE671BF-A3FE-44CE-88A5-2E21A205E809",
                "label": "Manitoba",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "EBAF4665-4E48-4CE1-AEAA-907F43FC48F8",
                "label": "Marshall Islands",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "C94E2621-A7C1-4A24-B980-8D0E3F7141D3",
                "label": "Maryland",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "959173D1-BC62-4230-8C4B-CBBBBCFFB7AA",
                "label": "Massachusetts",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "98DE8096-3E24-4540-A3E2-F0550AB911E5",
                "label": "Michigan",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "37D94BB5-0165-4AA2-86F7-272957C31DEA",
                "label": "Minnesota",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D8F5DF72-EDBB-49FB-B984-1231622132E2",
                "label": "Mississippi",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "B7176E22-99A3-4342-9451-E341BD9F951D",
                "label": "Missouri",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "AC8E837C-B851-4230-AD85-81961E64DEBE",
                "label": "Montana",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "87AC38D1-89BC-4FD1-BFF0-C563D89891D4",
                "label": "Nebraska",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "DA67637E-A651-4ED9-A006-72391D72A173",
                "label": "Nevada",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "78BD957D-10D9-45CC-B3F9-FB7D60F56303",
                "label": "New Brunswick",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "52FAD62B-9284-4CB0-8B00-2F932CB8BE22",
                "label": "New Hampshire",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0D4CE7F2-8114-4529-805E-624587968E78",
                "label": "New Jersey",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "7CFF0B52-AC87-4BB7-8A47-FCCDA6DB3D64",
                "label": "New Mexico",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D3A347F7-82CF-4265-8EEE-C8C0DF44A13D",
                "label": "New York",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "1096FD80-1CA4-4B39-AC88-AA6D872A74DE",
                "label": "Newfoundland and Labrador",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "D9E19436-5006-4BD9-B645-B57E1B44901E",
                "label": "North Carolina",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E958FE6B-8BC7-494F-B4FB-5647333BB47D",
                "label": "North Dakota",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "445F1BF8-18E9-4FA2-AD40-D68ACDECEAF1",
                "label": "Northern Mariana Islands",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "A9CD03E7-5EDF-4CA5-8151-77DC110A5FC4",
                "label": "Northwest Territories",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "F416BA88-0685-4DB3-B8BC-FB8F5240DA1B",
                "label": "Nova Scotia",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "85D583A8-97C9-4982-B34B-54C0B1B6FCC0",
                "label": "Nunavut",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "330FF511-92D9-4A40-A1C5-E6E1F619BF21",
                "label": "Ohio",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "F85E595C-CF50-4C95-A19E-87A21FC3EA7A",
                "label": "Oklahoma",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "6955BCCA-ADB6-4834-B0A1-AF56EBF4E12D",
                "label": "Ontario",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "1C97444C-D9C2-48C9-9F88-1EA1E39FCF7E",
                "label": "Oregon",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "C5458F01-ED0D-4B2B-9B1C-29B60CF95260",
                "label": "Palau",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "14EBC5A3-1915-4663-AB33-D8BC6EDCEBF6",
                "label": "Pennsylvania",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "5A3BA6CB-DD4F-4B68-8021-86008472866D",
                "label": "Prince Edward Island",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "9E9427D9-E66C-452D-B9FE-B5AB89226C0C",
                "label": "Puerto Rico",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "641BACFD-AA6B-45A1-A77E-014FD7A13AC1",
                "label": "Quebec",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "0BCA8E0D-AE96-47E7-AD1A-F9713EF1EF50",
                "label": "Rhode Island",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "98014FEA-E450-428C-8289-C8079F4E3465",
                "label": "Saskatchewan",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "880B0895-D566-4A41-B199-745AA573D1EA",
                "label": "South Carolina",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "4E4D5737-9B4C-47A2-8A0A-DA450BE85946",
                "label": "South Dakota",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3E2E1BA8-C3A7-4EEF-A78A-7ADED342E155",
                "label": "Tennessee",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "B2564B9F-CC40-42F0-901F-43D7DB93E9B4",
                "label": "Texas",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "AB74F53E-5E76-4D5B-A758-44EC5F88EE0E",
                "label": "Utah",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "3841E2DF-A529-4431-92F4-76979CCE951C",
                "label": "Vermont",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "8C02A109-9764-4969-9067-B3461414D3B0",
                "label": "Virgin Islands",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "5D30B732-AC35-4066-B4F5-B745ED3878D2",
                "label": "Virginia",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "4930BF96-F21F-4DC1-A483-5AB581901FBB",
                "label": "Washington",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "854B07D0-162C-4ABD-8DDA-BC9D41F63004",
                "label": "West Virginia",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "CFF4F066-1979-488D-9929-DEFEE76ECD9B",
                "label": "Wisconsin",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "E8457244-BC93-4A43-9442-9D8CD30C5539",
                "label": "Wyoming",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            },
            {
                "id": "642B130F-B409-45A8-9225-5E927A3A863C",
                "label": "Yukon",
                "flag": "",
                "formelementid": "6811D874-DAC7-4BCC-8F7C-8822472AD538",
                "nextstructtype": "",
                "nextsp": "",
                "parentobjname": "formelements",
                "childobjname": "selectoptions",
                "parentid": "formelementid",
                "childid": "formelementid"
            }
        ]
    },
    {
        "formid": "93510045-2A1B-493B-98B7-4BEDF671CE00",
        "formelementid": "B910A971-7A56-414A-B74A-A3C334772409",
        "label": "Zip Code",
        "sequence": 22,
        "defaultvalue": "27401",
        "validminimum": 0,
        "validmaximum": 99999,
        "masktype": "",
        "datatype": "int",
        "canedit": 0,
        "required": 0,
        "groupid": "Billing Contact",
        "allowmultiplepicklistselections": 0,
        "saveparam": "BillingZipCodeProfile",
        "nextstructtype": "StepWithSoftwareUser",
        "nextsp": "exec [spxd_Form_Get_CustomerEditsCustomer_FormElements_SelectOptions] @SoftwareUserID = '%v'",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid",
        "selectoptions": []
    }
]