export const formtestingdates = [
    {
        "formid": "E8857009-0033-4725-9315-D40EAFEF263A",
        "formelementid": "809C88A0-D1B1-48E4-B3A3-8F0F6650A9DC",
        "label": "Input Passing",
        "sequence": 0,
        "defaultvalue": "D4F69A74-6F3B-4B17-BAED-03B0C188A4B1",
        "validminimum": 0,
        "validmaximum": 40,
        "masktype": "",
        "datatype": "string",
        "canedit": 0,
        "hidden": 1,
        "required": 0,
        "allowmultiplepicklistselections": 0,
        "saveparam": "NewHolidayID",
        "requiredbystep": "ECD3B7A9-E8AA-4487-B276-4DEC0675DF9B",
        "fieldname": "NewHolidayID",
        "nextstructtype": "",
        "nextsp": "",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid"
    },
    {
        "formid": "E8857009-0033-4725-9315-D40EAFEF263A",
        "formelementid": "BDA81AEE-E912-4A49-84D6-F86C39DA5B85",
        "label": "New Holiday Date",
        "sequence": 0,
        "defaultvalue": "",
        "validminimum": 0,
        "validmaximum": 1,
        "masktype": "date",
        "datatype": "datetime",
        "canedit": 1,
        "hidden": 0,
        "required": 1,
        "allowmultiplepicklistselections": 0,
        "saveparam": "HolidayDate",
        "requiredbystep": "",
        "fieldname": "",
        "nextstructtype": "",
        "nextsp": "",
        "parentobjname": "form",
        "childobjname": "formelements",
        "parentid": "formid",
        "childid": "formid"
    }
]