name: Build & Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install dependencies
        run: yarn

      # Build the packages
      - name: Build packages
        run: yarn build

      # Run automated tests
      - name: Automated tests
        run: yarn test

